package main

import (
	"encoding/json"
	"fmt"
)

type AutoGenerated struct {
	Tracks struct {
		Href  string `json:"href"`
		Items []struct {
			Album struct {
				AlbumType string `json:"album_type"`
				Artists   []struct {
					ExternalUrls struct {
						Spotify string `json:"spotify"`
					} `json:"external_urls"`
					Href string `json:"href"`
					ID   string `json:"id"`
					Name string `json:"name"`
					Type string `json:"type"`
					URI  string `json:"uri"`
				} `json:"artists"`
				ExternalUrls struct {
					Spotify string `json:"spotify"`
				} `json:"external_urls"`
				Href   string `json:"href"`
				ID     string `json:"id"`
				Images []struct {
					Height int    `json:"height"`
					URL    string `json:"url"`
					Width  int    `json:"width"`
				} `json:"images"`
				Name                 string `json:"name"`
				ReleaseDate          string `json:"release_date"`
				ReleaseDatePrecision string `json:"release_date_precision"`
				TotalTracks          int    `json:"total_tracks"`
				Type                 string `json:"type"`
				URI                  string `json:"uri"`
			} `json:"album"`
			Artists []struct {
				ExternalUrls struct {
					Spotify string `json:"spotify"`
				} `json:"external_urls"`
				Href string `json:"href"`
				ID   string `json:"id"`
				Name string `json:"name"`
				Type string `json:"type"`
				URI  string `json:"uri"`
			} `json:"artists"`
			DiscNumber  int  `json:"disc_number"`
			DurationMs  int  `json:"duration_ms"`
			Explicit    bool `json:"explicit"`
			ExternalIds struct {
				Isrc string `json:"isrc"`
			} `json:"external_ids"`
			ExternalUrls struct {
				Spotify string `json:"spotify"`
			} `json:"external_urls"`
			Href        string `json:"href"`
			ID          string `json:"id"`
			IsLocal     bool   `json:"is_local"`
			IsPlayable  bool   `json:"is_playable"`
			Name        string `json:"name"`
			Popularity  int    `json:"popularity"`
			PreviewURL  string `json:"preview_url"`
			TrackNumber int    `json:"track_number"`
			Type        string `json:"type"`
			URI         string `json:"uri"`
		} `json:"items"`
		Limit    int    `json:"limit"`
		Next     string `json:"next"`
		Offset   int    `json:"offset"`
		Previous string `json:"previous"`
		Total    int    `json:"total"`
	} `json:"tracks"`
}

func main() {
	b := []byte(`{
    "tracks": {
        "href": "https://api.spotify.com/v1/search?query=hillsong&type=track&market=ES&offset=1&limit=10",
        "items": [
            {
                "album": {
                    "album_type": "album",
                    "artists": [
                        {
                            "external_urls": {
                                "spotify": "https://open.spotify.com/artist/74cb3MG0x0BOnYNW1uXYnM"
                            },
                            "href": "https://api.spotify.com/v1/artists/74cb3MG0x0BOnYNW1uXYnM",
                            "id": "74cb3MG0x0BOnYNW1uXYnM",
                            "name": "Hillsong United",
                            "type": "artist",
                            "uri": "spotify:artist:74cb3MG0x0BOnYNW1uXYnM"
                        }
                    ],
                    "external_urls": {
                        "spotify": "https://open.spotify.com/album/7LHFVlsndw7HxDGJPWJS7S"
                    },
                    "href": "https://api.spotify.com/v1/albums/7LHFVlsndw7HxDGJPWJS7S",
                    "id": "7LHFVlsndw7HxDGJPWJS7S",
                    "images": [
                        {
                            "height": 640,
                            "url": "https://i.scdn.co/image/0880157e603e34b1e2183aa5b77e22c04465c439",
                            "width": 640
                        },
                        {
                            "height": 300,
                            "url": "https://i.scdn.co/image/16ae3555429e74456ad9b349b7576f2a3af838f3",
                            "width": 300
                        },
                        {
                            "height": 64,
                            "url": "https://i.scdn.co/image/d3439186074719806ed430d2c0ac78dbada31c9f",
                            "width": 64
                        }
                    ],
                    "name": "Zion",
                    "release_date": "2013-02-23",
                    "release_date_precision": "day",
                    "total_tracks": 13,
                    "type": "album",
                    "uri": "spotify:album:7LHFVlsndw7HxDGJPWJS7S"
                },
                "artists": [
                    {
                        "external_urls": {
                            "spotify": "https://open.spotify.com/artist/74cb3MG0x0BOnYNW1uXYnM"
                        },
                        "href": "https://api.spotify.com/v1/artists/74cb3MG0x0BOnYNW1uXYnM",
                        "id": "74cb3MG0x0BOnYNW1uXYnM",
                        "name": "Hillsong United",
                        "type": "artist",
                        "uri": "spotify:artist:74cb3MG0x0BOnYNW1uXYnM"
                    }
                ],
                "disc_number": 1,
                "duration_ms": 536000,
                "explicit": false,
                "external_ids": {
                    "isrc": "AUHS01205284"
                },
                "external_urls": {
                    "spotify": "https://open.spotify.com/track/5SDcksP8En1l6RtTY1wzHc"
                },
                "href": "https://api.spotify.com/v1/tracks/5SDcksP8En1l6RtTY1wzHc",
                "id": "5SDcksP8En1l6RtTY1wzHc",
                "is_local": false,
                "is_playable": true,
                "name": "Oceans (Where Feet May Fail)",
                "popularity": 64,
                "preview_url": "https://p.scdn.co/mp3-preview/2b4ff4c0d5358f7dbf85bf924a27c2ca7f6db8ac?cid=774b29d4f13844c495f206cafdad9c86",
                "track_number": 4,
                "type": "track",
                "uri": "spotify:track:5SDcksP8En1l6RtTY1wzHc"
            },
            {
                "album": {
                    "album_type": "album",
                    "artists": [
                        {
                            "external_urls": {
                                "spotify": "https://open.spotify.com/artist/3SgHzT552wy2W8pNLaLk24"
                            },
                            "href": "https://api.spotify.com/v1/artists/3SgHzT552wy2W8pNLaLk24",
                            "id": "3SgHzT552wy2W8pNLaLk24",
                            "name": "Hillsong Worship",
                            "type": "artist",
                            "uri": "spotify:artist:3SgHzT552wy2W8pNLaLk24"
                        }
                    ],
                    "external_urls": {
                        "spotify": "https://open.spotify.com/album/6MQZ9pVXzVsA50a0wYFImm"
                    },
                    "href": "https://api.spotify.com/v1/albums/6MQZ9pVXzVsA50a0wYFImm",
                    "id": "6MQZ9pVXzVsA50a0wYFImm",
                    "images": [
                        {
                            "height": 640,
                            "url": "https://i.scdn.co/image/8ce22e44de6bea4316fe218adcfc06a35a48946e",
                            "width": 640
                        },
                        {
                            "height": 300,
                            "url": "https://i.scdn.co/image/f8340070e289312f7d2230d051b48161ff33419e",
                            "width": 300
                        },
                        {
                            "height": 64,
                            "url": "https://i.scdn.co/image/a0adcac3d1b93153c07bf0a9b921cdbf73d03983",
                            "width": 64
                        }
                    ],
                    "name": "There Is More",
                    "release_date": "2018-04-06",
                    "release_date_precision": "day",
                    "total_tracks": 17,
                    "type": "album",
                    "uri": "spotify:album:6MQZ9pVXzVsA50a0wYFImm"
                },
                "artists": [
                    {
                        "external_urls": {
                            "spotify": "https://open.spotify.com/artist/3SgHzT552wy2W8pNLaLk24"
                        },
                        "href": "https://api.spotify.com/v1/artists/3SgHzT552wy2W8pNLaLk24",
                        "id": "3SgHzT552wy2W8pNLaLk24",
                        "name": "Hillsong Worship",
                        "type": "artist",
                        "uri": "spotify:artist:3SgHzT552wy2W8pNLaLk24"
                    }
                ],
                "disc_number": 1,
                "duration_ms": 329080,
                "explicit": false,
                "external_ids": {
                    "isrc": "AUHS01809738"
                },
                "external_urls": {
                    "spotify": "https://open.spotify.com/track/50lW1fKoDtyKaiR2bR7ksl"
                },
                "href": "https://api.spotify.com/v1/tracks/50lW1fKoDtyKaiR2bR7ksl",
                "id": "50lW1fKoDtyKaiR2bR7ksl",
                "is_local": false,
                "is_playable": true,
                "name": "Who You Say I Am",
                "popularity": 63,
                "preview_url": "https://p.scdn.co/mp3-preview/0405a4ac8cf6eb758a5dcc9203ae8f2f451d6d5a?cid=774b29d4f13844c495f206cafdad9c86",
                "track_number": 1,
                "type": "track",
                "uri": "spotify:track:50lW1fKoDtyKaiR2bR7ksl"
            },
            {
                "album": {
                    "album_type": "single",
                    "artists": [
                        {
                            "external_urls": {
                                "spotify": "https://open.spotify.com/artist/3SgHzT552wy2W8pNLaLk24"
                            },
                            "href": "https://api.spotify.com/v1/artists/3SgHzT552wy2W8pNLaLk24",
                            "id": "3SgHzT552wy2W8pNLaLk24",
                            "name": "Hillsong Worship",
                            "type": "artist",
                            "uri": "spotify:artist:3SgHzT552wy2W8pNLaLk24"
                        }
                    ],
                    "external_urls": {
                        "spotify": "https://open.spotify.com/album/5tYHku7MpOJjUecn5Ape0O"
                    },
                    "href": "https://api.spotify.com/v1/albums/5tYHku7MpOJjUecn5Ape0O",
                    "id": "5tYHku7MpOJjUecn5Ape0O",
                    "images": [
                        {
                            "height": 640,
                            "url": "https://i.scdn.co/image/8bc9601ac59fc2dea4eb6b33f596ca9494d4b180",
                            "width": 640
                        },
                        {
                            "height": 300,
                            "url": "https://i.scdn.co/image/1e04a96e22f116839c2ee79e926118d0cb783390",
                            "width": 300
                        },
                        {
                            "height": 64,
                            "url": "https://i.scdn.co/image/879b1987d74743c25474e59788a8dc1098128edf",
                            "width": 64
                        }
                    ],
                    "name": "What A Beautiful Name",
                    "release_date": "2017-01-06",
                    "release_date_precision": "day",
                    "total_tracks": 1,
                    "type": "album",
                    "uri": "spotify:album:5tYHku7MpOJjUecn5Ape0O"
                },
                "artists": [
                    {
                        "external_urls": {
                            "spotify": "https://open.spotify.com/artist/3SgHzT552wy2W8pNLaLk24"
                        },
                        "href": "https://api.spotify.com/v1/artists/3SgHzT552wy2W8pNLaLk24",
                        "id": "3SgHzT552wy2W8pNLaLk24",
                        "name": "Hillsong Worship",
                        "type": "artist",
                        "uri": "spotify:artist:3SgHzT552wy2W8pNLaLk24"
                    }
                ],
                "disc_number": 1,
                "duration_ms": 240200,
                "explicit": false,
                "external_ids": {
                    "isrc": "AUHS01608837"
                },
                "external_urls": {
                    "spotify": "https://open.spotify.com/track/5XCtjnFMKtCT7ycDwV3Kdh"
                },
                "href": "https://api.spotify.com/v1/tracks/5XCtjnFMKtCT7ycDwV3Kdh",
                "id": "5XCtjnFMKtCT7ycDwV3Kdh",
                "is_local": false,
                "is_playable": true,
                "name": "What A Beautiful Name",
                "popularity": 60,
                "preview_url": "https://p.scdn.co/mp3-preview/d37abfe9bf932b12b2a7af7c4177d293dbee272c?cid=774b29d4f13844c495f206cafdad9c86",
                "track_number": 1,
                "type": "track",
                "uri": "spotify:track:5XCtjnFMKtCT7ycDwV3Kdh"
            },
            {
                "album": {
                    "album_type": "album",
                    "artists": [
                        {
                            "external_urls": {
                                "spotify": "https://open.spotify.com/artist/3phVKYqeq84Ai91CHTQfNq"
                            },
                            "href": "https://api.spotify.com/v1/artists/3phVKYqeq84Ai91CHTQfNq",
                            "id": "3phVKYqeq84Ai91CHTQfNq",
                            "name": "Hillsong en Español",
                            "type": "artist",
                            "uri": "spotify:artist:3phVKYqeq84Ai91CHTQfNq"
                        }
                    ],
                    "external_urls": {
                        "spotify": "https://open.spotify.com/album/20Jz9tXb633PF9nGukskgE"
                    },
                    "href": "https://api.spotify.com/v1/albums/20Jz9tXb633PF9nGukskgE",
                    "id": "20Jz9tXb633PF9nGukskgE",
                    "images": [
                        {
                            "height": 640,
                            "url": "https://i.scdn.co/image/82ec7a7225dda7ab0875d737c19c08813c04a943",
                            "width": 640
                        },
                        {
                            "height": 300,
                            "url": "https://i.scdn.co/image/15def8d2c3427c8ed89e768aa81f8e03c1637693",
                            "width": 300
                        },
                        {
                            "height": 64,
                            "url": "https://i.scdn.co/image/2449cb89fdad3e7da7f10a7f21f1431b4142ccca",
                            "width": 64
                        }
                    ],
                    "name": "El Eco De Su Voz (Spanish)",
                    "release_date": "2017-04-28",
                    "release_date_precision": "day",
                    "total_tracks": 11,
                    "type": "album",
                    "uri": "spotify:album:20Jz9tXb633PF9nGukskgE"
                },
                "artists": [
                    {
                        "external_urls": {
                            "spotify": "https://open.spotify.com/artist/3phVKYqeq84Ai91CHTQfNq"
                        },
                        "href": "https://api.spotify.com/v1/artists/3phVKYqeq84Ai91CHTQfNq",
                        "id": "3phVKYqeq84Ai91CHTQfNq",
                        "name": "Hillsong en Español",
                        "type": "artist",
                        "uri": "spotify:artist:3phVKYqeq84Ai91CHTQfNq"
                    }
                ],
                "disc_number": 1,
                "duration_ms": 351600,
                "explicit": false,
                "external_ids": {
                    "isrc": "AUHS01608853"
                },
                "external_urls": {
                    "spotify": "https://open.spotify.com/track/7HAxoYUvYynHfn4vQFJr6d"
                },
                "href": "https://api.spotify.com/v1/tracks/7HAxoYUvYynHfn4vQFJr6d",
                "id": "7HAxoYUvYynHfn4vQFJr6d",
                "is_local": false,
                "is_playable": true,
                "name": "Hermoso Nombre",
                "popularity": 52,
                "preview_url": "https://p.scdn.co/mp3-preview/2ba40053efbc29f4e79757db7892bc49b25bd40e?cid=774b29d4f13844c495f206cafdad9c86",
                "track_number": 5,
                "type": "track",
                "uri": "spotify:track:7HAxoYUvYynHfn4vQFJr6d"
            },
            {
                "album": {
                    "album_type": "album",
                    "artists": [
                        {
                            "external_urls": {
                                "spotify": "https://open.spotify.com/artist/3SgHzT552wy2W8pNLaLk24"
                            },
                            "href": "https://api.spotify.com/v1/artists/3SgHzT552wy2W8pNLaLk24",
                            "id": "3SgHzT552wy2W8pNLaLk24",
                            "name": "Hillsong Worship",
                            "type": "artist",
                            "uri": "spotify:artist:3SgHzT552wy2W8pNLaLk24"
                        }
                    ],
                    "external_urls": {
                        "spotify": "https://open.spotify.com/album/6MQZ9pVXzVsA50a0wYFImm"
                    },
                    "href": "https://api.spotify.com/v1/albums/6MQZ9pVXzVsA50a0wYFImm",
                    "id": "6MQZ9pVXzVsA50a0wYFImm",
                    "images": [
                        {
                            "height": 640,
                            "url": "https://i.scdn.co/image/8ce22e44de6bea4316fe218adcfc06a35a48946e",
                            "width": 640
                        },
                        {
                            "height": 300,
                            "url": "https://i.scdn.co/image/f8340070e289312f7d2230d051b48161ff33419e",
                            "width": 300
                        },
                        {
                            "height": 64,
                            "url": "https://i.scdn.co/image/a0adcac3d1b93153c07bf0a9b921cdbf73d03983",
                            "width": 64
                        }
                    ],
                    "name": "There Is More",
                    "release_date": "2018-04-06",
                    "release_date_precision": "day",
                    "total_tracks": 17,
                    "type": "album",
                    "uri": "spotify:album:6MQZ9pVXzVsA50a0wYFImm"
                },
                "artists": [
                    {
                        "external_urls": {
                            "spotify": "https://open.spotify.com/artist/3SgHzT552wy2W8pNLaLk24"
                        },
                        "href": "https://api.spotify.com/v1/artists/3SgHzT552wy2W8pNLaLk24",
                        "id": "3SgHzT552wy2W8pNLaLk24",
                        "name": "Hillsong Worship",
                        "type": "artist",
                        "uri": "spotify:artist:3SgHzT552wy2W8pNLaLk24"
                    }
                ],
                "disc_number": 1,
                "duration_ms": 424386,
                "explicit": false,
                "external_ids": {
                    "isrc": "AUHS01809749"
                },
                "external_urls": {
                    "spotify": "https://open.spotify.com/track/3ebqpN2hFJNeTuTTI5G0nd"
                },
                "href": "https://api.spotify.com/v1/tracks/3ebqpN2hFJNeTuTTI5G0nd",
                "id": "3ebqpN2hFJNeTuTTI5G0nd",
                "is_local": false,
                "is_playable": true,
                "name": "So Will I (100 Billion X)",
                "popularity": 62,
                "preview_url": "https://p.scdn.co/mp3-preview/8da3bcf0aad2215e92e2f4c804f6cac1cafb15fe?cid=774b29d4f13844c495f206cafdad9c86",
                "track_number": 12,
                "type": "track",
                "uri": "spotify:track:3ebqpN2hFJNeTuTTI5G0nd"
            },
            {
                "album": {
                    "album_type": "album",
                    "artists": [
                        {
                            "external_urls": {
                                "spotify": "https://open.spotify.com/artist/3phVKYqeq84Ai91CHTQfNq"
                            },
                            "href": "https://api.spotify.com/v1/artists/3phVKYqeq84Ai91CHTQfNq",
                            "id": "3phVKYqeq84Ai91CHTQfNq",
                            "name": "Hillsong en Español",
                            "type": "artist",
                            "uri": "spotify:artist:3phVKYqeq84Ai91CHTQfNq"
                        }
                    ],
                    "external_urls": {
                        "spotify": "https://open.spotify.com/album/2bjV5XKKD0g4wDFnsWBVhi"
                    },
                    "href": "https://api.spotify.com/v1/albums/2bjV5XKKD0g4wDFnsWBVhi",
                    "id": "2bjV5XKKD0g4wDFnsWBVhi",
                    "images": [
                        {
                            "height": 640,
                            "url": "https://i.scdn.co/image/6fff597604cbe8a409e22d01b52d019bab929402",
                            "width": 640
                        },
                        {
                            "height": 300,
                            "url": "https://i.scdn.co/image/2055f4b3d61951efc20f3dc9e39a224799f9ca8a",
                            "width": 300
                        },
                        {
                            "height": 64,
                            "url": "https://i.scdn.co/image/020a5be6200ce3d4b977c507e9d58ff550a3eb59",
                            "width": 64
                        }
                    ],
                    "name": "En Esto Creo (Spanish)",
                    "release_date": "2015-08-07",
                    "release_date_precision": "day",
                    "total_tracks": 13,
                    "type": "album",
                    "uri": "spotify:album:2bjV5XKKD0g4wDFnsWBVhi"
                },
                "artists": [
                    {
                        "external_urls": {
                            "spotify": "https://open.spotify.com/artist/3phVKYqeq84Ai91CHTQfNq"
                        },
                        "href": "https://api.spotify.com/v1/artists/3phVKYqeq84Ai91CHTQfNq",
                        "id": "3phVKYqeq84Ai91CHTQfNq",
                        "name": "Hillsong en Español",
                        "type": "artist",
                        "uri": "spotify:artist:3phVKYqeq84Ai91CHTQfNq"
                    }
                ],
                "disc_number": 1,
                "duration_ms": 572413,
                "explicit": false,
                "external_ids": {
                    "isrc": "AUHS01507305"
                },
                "external_urls": {
                    "spotify": "https://open.spotify.com/track/3MHkeMZGfp6hNB5rsrEnBa"
                },
                "href": "https://api.spotify.com/v1/tracks/3MHkeMZGfp6hNB5rsrEnBa",
                "id": "3MHkeMZGfp6hNB5rsrEnBa",
                "is_local": false,
                "is_playable": true,
                "name": "Vasijas Rotas (Sublime Gracia)",
                "popularity": 51,
                "preview_url": "https://p.scdn.co/mp3-preview/82f34b435fc2d88a116d831a02c6fb4d295164af?cid=774b29d4f13844c495f206cafdad9c86",
                "track_number": 2,
                "type": "track",
                "uri": "spotify:track:3MHkeMZGfp6hNB5rsrEnBa"
            },
            {
                "album": {
                    "album_type": "album",
                    "artists": [
                        {
                            "external_urls": {
                                "spotify": "https://open.spotify.com/artist/3phVKYqeq84Ai91CHTQfNq"
                            },
                            "href": "https://api.spotify.com/v1/artists/3phVKYqeq84Ai91CHTQfNq",
                            "id": "3phVKYqeq84Ai91CHTQfNq",
                            "name": "Hillsong en Español",
                            "type": "artist",
                            "uri": "spotify:artist:3phVKYqeq84Ai91CHTQfNq"
                        }
                    ],
                    "external_urls": {
                        "spotify": "https://open.spotify.com/album/20Jz9tXb633PF9nGukskgE"
                    },
                    "href": "https://api.spotify.com/v1/albums/20Jz9tXb633PF9nGukskgE",
                    "id": "20Jz9tXb633PF9nGukskgE",
                    "images": [
                        {
                            "height": 640,
                            "url": "https://i.scdn.co/image/82ec7a7225dda7ab0875d737c19c08813c04a943",
                            "width": 640
                        },
                        {
                            "height": 300,
                            "url": "https://i.scdn.co/image/15def8d2c3427c8ed89e768aa81f8e03c1637693",
                            "width": 300
                        },
                        {
                            "height": 64,
                            "url": "https://i.scdn.co/image/2449cb89fdad3e7da7f10a7f21f1431b4142ccca",
                            "width": 64
                        }
                    ],
                    "name": "El Eco De Su Voz (Spanish)",
                    "release_date": "2017-04-28",
                    "release_date_precision": "day",
                    "total_tracks": 11,
                    "type": "album",
                    "uri": "spotify:album:20Jz9tXb633PF9nGukskgE"
                },
                "artists": [
                    {
                        "external_urls": {
                            "spotify": "https://open.spotify.com/artist/3phVKYqeq84Ai91CHTQfNq"
                        },
                        "href": "https://api.spotify.com/v1/artists/3phVKYqeq84Ai91CHTQfNq",
                        "id": "3phVKYqeq84Ai91CHTQfNq",
                        "name": "Hillsong en Español",
                        "type": "artist",
                        "uri": "spotify:artist:3phVKYqeq84Ai91CHTQfNq"
                    }
                ],
                "disc_number": 1,
                "duration_ms": 301000,
                "explicit": false,
                "external_ids": {
                    "isrc": "AUHS01608848"
                },
                "external_urls": {
                    "spotify": "https://open.spotify.com/track/4gjrqMJtwMONHe0nnjqiUq"
                },
                "href": "https://api.spotify.com/v1/tracks/4gjrqMJtwMONHe0nnjqiUq",
                "id": "4gjrqMJtwMONHe0nnjqiUq",
                "is_local": false,
                "is_playable": true,
                "name": "Amor Sin Comparación",
                "popularity": 51,
                "preview_url": "https://p.scdn.co/mp3-preview/bafbe2461fe916ab18e631eb6815af5bdd9f3c20?cid=774b29d4f13844c495f206cafdad9c86",
                "track_number": 2,
                "type": "track",
                "uri": "spotify:track:4gjrqMJtwMONHe0nnjqiUq"
            },
            {
                "album": {
                    "album_type": "album",
                    "artists": [
                        {
                            "external_urls": {
                                "spotify": "https://open.spotify.com/artist/3phVKYqeq84Ai91CHTQfNq"
                            },
                            "href": "https://api.spotify.com/v1/artists/3phVKYqeq84Ai91CHTQfNq",
                            "id": "3phVKYqeq84Ai91CHTQfNq",
                            "name": "Hillsong en Español",
                            "type": "artist",
                            "uri": "spotify:artist:3phVKYqeq84Ai91CHTQfNq"
                        }
                    ],
                    "external_urls": {
                        "spotify": "https://open.spotify.com/album/2bjV5XKKD0g4wDFnsWBVhi"
                    },
                    "href": "https://api.spotify.com/v1/albums/2bjV5XKKD0g4wDFnsWBVhi",
                    "id": "2bjV5XKKD0g4wDFnsWBVhi",
                    "images": [
                        {
                            "height": 640,
                            "url": "https://i.scdn.co/image/6fff597604cbe8a409e22d01b52d019bab929402",
                            "width": 640
                        },
                        {
                            "height": 300,
                            "url": "https://i.scdn.co/image/2055f4b3d61951efc20f3dc9e39a224799f9ca8a",
                            "width": 300
                        },
                        {
                            "height": 64,
                            "url": "https://i.scdn.co/image/020a5be6200ce3d4b977c507e9d58ff550a3eb59",
                            "width": 64
                        }
                    ],
                    "name": "En Esto Creo (Spanish)",
                    "release_date": "2015-08-07",
                    "release_date_precision": "day",
                    "total_tracks": 13,
                    "type": "album",
                    "uri": "spotify:album:2bjV5XKKD0g4wDFnsWBVhi"
                },
                "artists": [
                    {
                        "external_urls": {
                            "spotify": "https://open.spotify.com/artist/3phVKYqeq84Ai91CHTQfNq"
                        },
                        "href": "https://api.spotify.com/v1/artists/3phVKYqeq84Ai91CHTQfNq",
                        "id": "3phVKYqeq84Ai91CHTQfNq",
                        "name": "Hillsong en Español",
                        "type": "artist",
                        "uri": "spotify:artist:3phVKYqeq84Ai91CHTQfNq"
                    }
                ],
                "disc_number": 1,
                "duration_ms": 411360,
                "explicit": false,
                "external_ids": {
                    "isrc": "AUHS01507307"
                },
                "external_urls": {
                    "spotify": "https://open.spotify.com/track/2Vg9LaZqF2FK5mex92nypo"
                },
                "href": "https://api.spotify.com/v1/tracks/2Vg9LaZqF2FK5mex92nypo",
                "id": "2Vg9LaZqF2FK5mex92nypo",
                "is_local": false,
                "is_playable": true,
                "name": "Mi Roca",
                "popularity": 49,
                "preview_url": "https://p.scdn.co/mp3-preview/bbeed5f62152390deffccf0c37501cafe83c4870?cid=774b29d4f13844c495f206cafdad9c86",
                "track_number": 4,
                "type": "track",
                "uri": "spotify:track:2Vg9LaZqF2FK5mex92nypo"
            },
            {
                "album": {
                    "album_type": "album",
                    "artists": [
                        {
                            "external_urls": {
                                "spotify": "https://open.spotify.com/artist/3SgHzT552wy2W8pNLaLk24"
                            },
                            "href": "https://api.spotify.com/v1/artists/3SgHzT552wy2W8pNLaLk24",
                            "id": "3SgHzT552wy2W8pNLaLk24",
                            "name": "Hillsong Worship",
                            "type": "artist",
                            "uri": "spotify:artist:3SgHzT552wy2W8pNLaLk24"
                        }
                    ],
                    "external_urls": {
                        "spotify": "https://open.spotify.com/album/4qKQSjyrG1mS84P5tgX7ks"
                    },
                    "href": "https://api.spotify.com/v1/albums/4qKQSjyrG1mS84P5tgX7ks",
                    "id": "4qKQSjyrG1mS84P5tgX7ks",
                    "images": [
                        {
                            "height": 640,
                            "url": "https://i.scdn.co/image/8110637a13b697c59caad765a976c1d0f889d9d8",
                            "width": 640
                        },
                        {
                            "height": 300,
                            "url": "https://i.scdn.co/image/deeeb213164a1b201aabef6c78c73648df1fd7f8",
                            "width": 300
                        },
                        {
                            "height": 64,
                            "url": "https://i.scdn.co/image/570eaa876887af5bd98bfa5d6906f9807c3200ba",
                            "width": 64
                        }
                    ],
                    "name": "No Other Name",
                    "release_date": "2014-07-01",
                    "release_date_precision": "day",
                    "total_tracks": 11,
                    "type": "album",
                    "uri": "spotify:album:4qKQSjyrG1mS84P5tgX7ks"
                },
                "artists": [
                    {
                        "external_urls": {
                            "spotify": "https://open.spotify.com/artist/3SgHzT552wy2W8pNLaLk24"
                        },
                        "href": "https://api.spotify.com/v1/artists/3SgHzT552wy2W8pNLaLk24",
                        "id": "3SgHzT552wy2W8pNLaLk24",
                        "name": "Hillsong Worship",
                        "type": "artist",
                        "uri": "spotify:artist:3SgHzT552wy2W8pNLaLk24"
                    }
                ],
                "disc_number": 1,
                "duration_ms": 568791,
                "explicit": false,
                "external_ids": {
                    "isrc": "AUHS01406572"
                },
                "external_urls": {
                    "spotify": "https://open.spotify.com/track/35WtFQK3iG2WPjstuuKaVc"
                },
                "href": "https://api.spotify.com/v1/tracks/35WtFQK3iG2WPjstuuKaVc",
                "id": "35WtFQK3iG2WPjstuuKaVc",
                "is_local": false,
                "is_playable": true,
                "name": "Broken Vessels (Amazing Grace)",
                "popularity": 61,
                "preview_url": "https://p.scdn.co/mp3-preview/280f73cd7aa57e089e3300d5471c37a095323886?cid=774b29d4f13844c495f206cafdad9c86",
                "track_number": 3,
                "type": "track",
                "uri": "spotify:track:35WtFQK3iG2WPjstuuKaVc"
            },
            {
                "album": {
                    "album_type": "album",
                    "artists": [
                        {
                            "external_urls": {
                                "spotify": "https://open.spotify.com/artist/3SgHzT552wy2W8pNLaLk24"
                            },
                            "href": "https://api.spotify.com/v1/artists/3SgHzT552wy2W8pNLaLk24",
                            "id": "3SgHzT552wy2W8pNLaLk24",
                            "name": "Hillsong Worship",
                            "type": "artist",
                            "uri": "spotify:artist:3SgHzT552wy2W8pNLaLk24"
                        }
                    ],
                    "external_urls": {
                        "spotify": "https://open.spotify.com/album/5wBEavD9XYCXY6ALqFHeLW"
                    },
                    "href": "https://api.spotify.com/v1/albums/5wBEavD9XYCXY6ALqFHeLW",
                    "id": "5wBEavD9XYCXY6ALqFHeLW",
                    "images": [
                        {
                            "height": 640,
                            "url": "https://i.scdn.co/image/ad1ae3885526828855564918e707c6122794196a",
                            "width": 640
                        },
                        {
                            "height": 300,
                            "url": "https://i.scdn.co/image/98e2970a5173de57bf11c0ebe862720fcae26fda",
                            "width": 300
                        },
                        {
                            "height": 64,
                            "url": "https://i.scdn.co/image/072e35ddaae10d9bd759cc83b1d22bbcbe8c4cf9",
                            "width": 64
                        }
                    ],
                    "name": "Cornerstone (Live)",
                    "release_date": "2012-07-03",
                    "release_date_precision": "day",
                    "total_tracks": 13,
                    "type": "album",
                    "uri": "spotify:album:5wBEavD9XYCXY6ALqFHeLW"
                },
                "artists": [
                    {
                        "external_urls": {
                            "spotify": "https://open.spotify.com/artist/3SgHzT552wy2W8pNLaLk24"
                        },
                        "href": "https://api.spotify.com/v1/artists/3SgHzT552wy2W8pNLaLk24",
                        "id": "3SgHzT552wy2W8pNLaLk24",
                        "name": "Hillsong Worship",
                        "type": "artist",
                        "uri": "spotify:artist:3SgHzT552wy2W8pNLaLk24"
                    }
                ],
                "disc_number": 1,
                "duration_ms": 346346,
                "explicit": false,
                "external_ids": {
                    "isrc": "AUHS01204884"
                },
                "external_urls": {
                    "spotify": "https://open.spotify.com/track/4irEfIEfEXuaPVOYDCw5Rm"
                },
                "href": "https://api.spotify.com/v1/tracks/4irEfIEfEXuaPVOYDCw5Rm",
                "id": "4irEfIEfEXuaPVOYDCw5Rm",
                "is_local": false,
                "is_playable": true,
                "name": "I Surrender",
                "popularity": 55,
                "preview_url": "https://p.scdn.co/mp3-preview/6f651482ccc1531cf781318cbe513ac061352b7f?cid=774b29d4f13844c495f206cafdad9c86",
                "track_number": 4,
                "type": "track",
                "uri": "spotify:track:4irEfIEfEXuaPVOYDCw5Rm"
            }
        ],
        "limit": 10,
        "next": "https://api.spotify.com/v1/search?query=hillsong&type=track&market=ES&offset=11&limit=10",
        "offset": 1,
        "previous": "https://api.spotify.com/v1/search?query=hillsong&type=track&market=ES&offset=0&limit=10",
        "total": 2385
    }
}`)
	var m AutoGenerated
	if err := json.Unmarshal(b, &m); err != nil {
		fmt.Println(err)
		return
	}
	for i := 0; i < m.Tracks.Limit; i++ {
		fmt.Println("Album ", m.Tracks.Items[i].Album.Name)
	}

}
